### ISSUE TITLE
Samsung S9 false positive if in developer mode

### ISSUE THREAD

**Issue by jeffp26** [scottyab/rootbeer#111] opened 2019-12-05 18:06 UTC
My phone is not rooted, just developer mode turned on and I get a positive result.  I turn off developer mode and the result is negative.  Is this expected behavior?  Just because I have developer mode turned on does not mean the phone is rooted.

**Comment by stealthcopter** [comment] 2019-12-23 10:31
This is quite interesting and no it is not intended behaviour. Can you provide some more details (logs and which tests are returning positive). If you run the sample app it will provide logs and a visual idea of what tests are returning the false positive.

**Comment by stealthcopter** [comment] 2020-02-03 21:30
In the upcoming release we've removed busybox from the default root checks, this should hopefully fix many of the problems with false positives. I'm closing this issue but please re-open if you get a false positive with 0.0.8 onwards.
Thanks!

**Closed by stealthcopter** 2020-02-03 21:30 UTC
Labels: false positive
